import { Metadata } from 'next';
import RootLayout from '../layout';

export const metadata: Metadata = {
  title: 'User LIFF for App Router',
  description: 'Generated by create next app',
};

export default RootLayout;
